### ISSUE TITLE
Duplicated Content-Type when set this field

### ISSUE THREAD

**Issue by xinz** [benoitc/hackney#388]
Hi,

I'm using httpoison client occur the following issue, when add the "Content-Type" key-value pair in the http request header, we will get the duplicated content-type as an invalid case, e.g.

```Elixir
HTTPoison.post "http://httparrot.herokuapp.com/post", "{\"body\": \"test\"}", [{"Content-Type", "application/json"}]```

Since the hackney will automatically append the content-type in the requester header, when we set this field, the requested server will receive the "Content-Type: application/json, application/json" in the above sample post request.

I find the following code in `hackney_headers.erl` :

```Erlang
%% @doc extend the headers with a new list of `{Key, Value}' pair.
update(Headers, KVs) ->
  lists:foldl(fun
                ({K, V}, D) ->
                  insert(hackney_bstr:to_binary(K), hackney_bstr:to_binary(V), D);
                ({K, V, P}, D) ->
                  insert(hackney_bstr:to_binary(K), header_value(V, P), D)
              end, Headers, KVs).
```

```Erlang
%% @doc Insert the pair into the headers, merging with any pre-existing key.
%% A merge is done with Value = V0 ++ ", " ++ V1.
insert(Key, Value, Headers) ->
  Key1 = hackney_bstr:to_lower(Key),
  Value1 = case dict:find(Key1, Headers) of
             {ok, {_, OldValue}} ->
               << OldValue/binary, ", ", Value/binary >>;
             _ ->
               Value
           end,
  dict:store(Key1, {Key, Value1}, Headers).
```

The update `Headers` key-value pairs will use the `<< OldValue/binary, ", ", Value/binary >>` to splice them, but I think here should be replace the old value with the new value, any advise about it?

Thanks in advance!

**Comment by benoitc** [comment]
SO previous behaviour was replacing the old header which was unwanted. (see last commit). The question is why do you have the header twice?

**Comment by jayjun** [comment]
This change broke ExAws, see CargoSense/ex_aws#366.

**Comment by benwilson512** [comment]
Can someone clarify exactly what has changed? To my knowledge I wasn't relying on hackney to clobber headers for me. However if I was in fact specifying headers twice that's a bug on my end.

**Comment by jayjun** [comment]
@benwilson512 See CargoSense/ex_aws#368 for a downstream fix.

**Comment by xinz** [comment]
@benoitc , I want to call a POST request with XML string, the server side expects to receive the "Content-Type: text/xml", when I using httpoison (base on hackney), set the `Content-Type` field in the header of the client, the hackeny will append `Content-Type` base on the request `body` by default, so once you set the `Content-Type` when initialize http client, the server side will receive a duplicated value in the format as "***, ***".

Hope this is clarify for you.

**Comment by benoitc** [comment]
@benwilson512 the change related is https://github.com/benoitc/hackney/commit/29eae2bfc9abbb8015a308a3aebdf0776b9d9bee

the http specs specify that we have to send the multiple headers fiels, either appended or merged in one line separated by a comma. Curremt implementation does the second but will be changed soon to send headers line by line. see #386.

Anyway previous impementation was replacing headers and it was a bug. It's the responsability of the application to not send duplicate headers now.

**Comment by benoitc** [comment]
@jayjun good catch. i will fix the update to make it case insensitive

**Comment by benoitc** [comment]
@xinz hum  i don't understand. who is setting this duplicate header?

**Comment by xinz** [comment]
@benoitc , sorry that I didn't make it clear for you.  The `hackney` will set the duplicated(unexpected) value for the same key field in the HTTP header once when we custom the HTTP header field to send the HTTP request, it's easy to reproduce:

1, Step 1, we set the expected `Content-Type` in the HTTP header when send this post request

```elixir
HTTPoison.post "http://httparrot.herokuapp.com/post", "{\"body\": \"test\"}", [{"Content-Type", "application/json"}]
```

2, Step 2, the server side will receive the content-type field in the request's HTTP header as`"Content-Type": "application/json, application/json"` ,  NOT the expected `"Content-Type": "application/json"` in the http header.

**Comment by benwilson512** [comment]
Right, so it seems that the issue that affects ExAws specifically is that I specify a "host" header, but hackney adds a "Host" header after the fact, and the two get concatenated together.

**Comment by benoitc** [comment]
@xinz please send me a full trace so I will be able to see what's happening:

In Erlang: `hackney_trace:enable(max, io)`

**Comment by benoitc** [comment]
@benwilson512 on it. The patch will make in a way that hackney will only add an header if it's not exist.

**Comment by rlipscombe** [comment]
It appears to be _duplicating_ headers, not adding arbitrary ones:

```
hackney:post("http://localhost:15160",
    [{"content-type", "foo/bar"}], <<>>, []).
```

...results in...

```
POST /
{ 'content-type': 'foo/bar, foo/bar',
  'user-agent': 'hackney/1.6.6',
  host: 'localhost:15160',
  'content-length': '0' }
```

...where localhost:15160 is...

```
#!/usr/bin/env node

var http = require('http');
var server = http.createServer(function(req, res) {
    console.log(req.method + " " + req.url);
    console.log(req.headers);
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end("OK\n");
});
server.listen(15160, '127.0.0.1');
console.log("Listening on port 15160.");
```

**Comment by benoitc** [comment]
a new version will land tonight, i've been sidetracked.

**Comment by benoitc** [comment]
Can anyone affected by this issue test #390 . It should be fixed now, let me know.

**Comment by benoitc** [comment]
@xinz sounds like it works now:

```erlang
3> hackney:post(<<"http://httparrot.herokuapp.com/post" >>, [{<<"Content-Type">>, <<"application/json">>}], <<"{\"body\": \"test\"}">>, [with_body]).
{ok,200,
    [{<<"Connection">>,<<"keep-alive">>},
     {<<"Server">>,<<"Cowboy">>},
     {<<"Date">>,<<"Wed, 01 Mar 2017 14:52:19 GMT">>},
     {<<"Content-Length">>,<<"644">>},
     {<<"Content-Type">>,<<"application/json">>},
     {<<"Via">>,<<"1.1 vegur">>}],
    <<"{\n  \"args\": {},\n  \"headers\": {\n    \"host\": \"httparrot.herokuapp.com\",\n    \"connection\": \"close\",\n   "...>>}
4> 
```

and the json received:

```json
{
  "args": {},
  "headers": {
    "host": "httparrot.herokuapp.com",
    "connection": "close",
    "user-agent": "hackney/1.6.6",
    "content-type": "application/json",
    "x-request-id": "0efcbcbf-1d50-4c07-9a5f-6f7bc308dc3e",
    "x-forwarded-for": "90.109.55.31",
    "x-forwarded-proto": "http",
    "x-forwarded-port": "80",
    "via": "1.1 vegur",
    "connect-time": "0",
    "x-request-start": "1488379637897",
    "total-route-time": "0",
    "content-length": "16"
  },
  "url": "http://httparrot.herokuapp.com/post",
  "origin": "10.157.160.84",
  "form": {},
  "data": "{\"body\": \"test\"}",
  "json": {
    "body": "test"
  }
}```

**Comment by benoitc** [comment]
1.7.0 is now available on hex.pm

**Comment by xinz** [comment]
@benoitc , thanks for your work, it works now for my test.

And I find there are some syntax need to take care.

In the hackney 1.7.0, send an POST request in Erlang required as

```
Erlang
hackney:post("http://localhost:9001/test", [{<<"content-type">>, <<"foo/fee">>}], <<"123">>, []).
```

Before the hackney 1.7.0, we can set the key-value pair in header as string to send an POST request in Erlang

```
Erlang
hackney:post("http://localhost:9001/test", [{"content-type", "foo/fee"}], <<"123">>, []).
```

The above syntax difference is in the 1.7.0 release, it requires using `binary` type to match function in the hackney_headers_new module.

This syntax change may affect other open source projects which rely on the hackney, I test this case in httpoison (Elixir)

Before hackney 1.7.0, we can use the `keyword` type to set http header, it's working like this:

```
Elixir
headers = ["Content-Type": "text/xml"]
HTTPoison.post!("http://localhost:9001/test", "", headers, [])
```

In 1.7.0, if we still pass the keyword to set http header will get the similar error message

```
 (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.bit_size(:"Content-Type")
            (hackney) /Users/xinz/workshop/test/deps/hackney/src/hackney_bstr.erl:40: :hackney_bstr.to_lower/1
            (hackney) /Users/xinz/workshop/test/deps/hackney/src/hackney_headers_new.erl:63: :hackney_headers_new.append/3
            (stdlib) lists.erl:1263: :lists.foldl/3
            (hackney) /Users/xinz/workshop/test/deps/hackney/src/hackney.erl:328: :hackney.request/5
            (httpoison) lib/httpoison/base.ex:424: HTTPoison.Base.request/9
            (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
```

NOTICE: The httpoison's document writes using `[{binary, binary}] | %{binary => binary}` to set the headers

So if you have the above mentioned code syntax in Elixir/Erlang, please take care when you upgrade to hackney 1.7.0

**Comment by benoitc** [comment]
@xinz i will look at it, thanks for the report

**Comment by benoitc** [comment]
@xinz the regression has been fixed in 1.7.1 .

**Comment by xinz** [comment]
@benoitc , verified, thank a lot for your prompt update. With 1.7.1, the following Elixir code can work now.

```Elixir
headers = ["Content-Type": "text/xml"]
HTTPoison.post!("http://localhost:9001/test", "", headers, [])
```
