### ISSUE TITLE
Error in hackney_headers_new

### ISSUE THREAD

**Issue by pwightman** [benoitc/hackney#400]
hackney lib version: 0.7.1
httpoision lib version: 0.11.1

Using the `follow_redirect` option with a URL that redirects (`https://google.com/` redirects to `https://www.google.com/`) fails inside hackney's header parsing. It seems related to the recent header parsing refactor for duplicate headers (#234 and related).

HTTPoison code (tried to reproduce in only hackney but couldn't quite figure it out, sorry ☹️):

```
HTTPoison.get("https://google.com/", [], follow_redirect: true)
```

Error:

```
** (FunctionClauseError) no function clause matching in :hackney_headers_new.do_fold/3
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney_headers_new.erl:147: :hackney_headers_new.do_fold([[{1, "Host", 119}], [{2, "Host", 119}], [{3, "Host", 119}], [{4, "Host", 46}], [{5, "Host", 103}], [{6, "Host", 111}], [{7, "Host", 111}], [{8, "Host", 103}], [{9, "Host", 108}], [{10, "Host", 101}], [{11, "Host", 46}], [{12, "Host", 99}], [{13, "Host", 111}], [{14, "Host", 109}]], #Function<6.29524015/3 in :hackney_headers_new.to_iolist/1>, [["User-Agent", ': ', "hackney/1.7.1", '\r\n']])
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney_headers_new.erl:184: :hackney_headers_new.to_iolist/1
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney_request.erl:95: :hackney_request.perform/2
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney.erl:373: :hackney.send_request/2
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney.erl:823: :hackney.redirect/2
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney.erl:757: :hackney.maybe_redirect1/3
      (hackney) /Users/parkerwightman/cs/ohi/deps/hackney/src/hackney.erl:377: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
```

**Comment by pwightman** [comment]
Updated the Stacktrace above with actual parameter list passed into `hackney_headers_new.do_fold`.

**Comment by pwightman** [comment]
It would appear it has to to do with the `follow_redirects` option, even this fails with the same error:

```
HTTPoison.get("https://google.com/", [], follow_redirect: true)
```

**Comment by pwightman** [comment]
Initial issue updated to reflect minimum reproduction case.

**Comment by edevil** [comment]
Me too:
```
** (FunctionClauseError) no function clause matching in :hackney_headers_new.do_fold/3
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney_headers_new.erl:147: :hackney_headers_new.do_fold([[{1, "Host", 102}], [{2, "Host", 101}], [{3, "Host", 101}], [{4, "Host",
 100}], [{5, "Host", 115}], [{6, "Host", 46}], [{7, "Host", 102}], [{8, "Host", 101}], [{9, "Host", 101}], [{10, "Host", 100}], [{11, "Host", 98}], [{12, "Host", 117}], [{13, "Host", 114}], [{14
, "Host", 110}], [{15, "Host", 101}], [{16, "Host", 114}], [{17, "Host", 46}], [{18, "Host", 99}], [{19, "Host", 111}], [{20, "Host", 109}]], #Function<6.29524015/3 in :hackney_headers_new.to_io
list/1>, [["User-Agent", ': ', "hackney/1.7.1", '\r\n']])
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney_headers_new.erl:184: :hackney_headers_new.to_iolist/1
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney_request.erl:95: :hackney_request.perform/2
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney.erl:373: :hackney.send_request/2
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney.erl:823: :hackney.redirect/2
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney.erl:757: :hackney.maybe_redirect1/3
    (hackney) /home/travis/build/brpx/trendex/deps/hackney/src/hackney.erl:377: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
```

**Comment by benoitc** [comment]
are you sure about the version of hackney? Latest is 1.6.2 ...

When I tried your request it's working:
```
1> application:ensure_all_started(hackney).
{ok,[idna,mimerl,certifi,ssl_verify_fun,metrics,hackney]}
2> hackney:get("https://google.com/", [], <<>>, [folow_redirect]).
{ok,302,
    [{<<"Cache-Control">>,<<"private">>},
     {<<"Content-Type">>,<<"text/html; charset=UTF-8">>},
     {<<"Referrer-Policy">>,<<"no-referrer">>},
     {<<"Location">>,
      <<"https://www.google.fr/?gfe_rd=cr&ei=5jH4WNLxBcfS8Af12IiYBA">>},
     {<<"Content-Length">>,<<"259">>},
     {<<"Date">>,<<"Thu, 20 Apr 2017 03:58:30 GMT">>},
     {<<"Alt-Svc">>,
      <<"quic=\":443\"; ma=2592000; v=\"37,36,35\"">>}],
    #Ref<0.0.1.2425>}
```
