### ISSUE TITLE
module :certifi is not available

### ISSUE THREAD

**Issue by bbtdev** [benoitc/hackney#517]
Hello,
I try running this test, on other macbooks it works, I don't undestand what is the problem:

```
** (UndefinedFunctionError) function :certifi.cacerts/0 is undefined (module :certifi is not available)
    (certifi) :certifi.cacerts()
    (hackney) /Users/bogdan/Documents/Projects/z/carts-api/deps/hackney/src/hackney_connect.erl:296: :hackney_connect.ss
l_opts_1/2
    (hackney) /Users/bogdan/Documents/Projects/z/carts-api/deps/hackney/src/hackney_connect.erl:243: :hackney_connect.do
_connect/5
    (hackney) /Users/bogdan/Documents/Projects/z/carts-api/deps/hackney/src/hackney_connect.erl:37: :hackney_connect.con
nect/5
    (hackney) /Users/bogdan/Documents/Projects/z/carts-api/deps/hackney/src/hackney.erl:316: :hackney.request/5
    (oauth2) lib/oauth2/request.ex:23: OAuth2.Request.request/6
    (oauth2) lib/oauth2/client.ex:231: OAuth2.Client.get_token/4
    (carts_service) lib/carts_service/utils/oauth2_helper.ex:39: Carts.Service.Utils.Oauth2Helper.get_token/3
    (carts_service) lib/carts_service/customer/helpers/login_customer_helper.ex:22: Carts.Service.LoginCustomerHelper.login/3
    (carts_service) lib/carts_service/customer/customer.ex:180: Carts.Service.Customer.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

My knowlegde of certificates is very limited, I can't find any information about this certain issue

**Comment by benoitc** [comment]
seems like the application certifi has not been fetched by your mix build. Can you past me the full og of it if you have it?

**Comment by bbtdev** [comment]
@benoitc Hey thank you for your intereset, I deleted the local repo, cloned and did mix deps.get there is no problem now. I can't replicate it. If I encounter this I will reopen the issue.

Have a great weekend!

**Comment by axelson** [comment]
Posting this potentially related issue for anyone stumbling here: https://github.com/benoitc/hackney/issues/528
