### ISSUE TITLE
(FunctionClauseError) no function clause matching in :hackney_headers_new.params_to_iolist/2

### ISSUE THREAD

**Issue by silva96** [benoitc/hackney#642]
Hi, im using httpoison 1.6.2 which uses hackney 1.16.0

Some requests are failing with :closed

```
stacktrace:
** (FunctionClauseError) no function clause matching in :hackney_headers_new.params_to_iolist/2
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:201: :hackney_headers_new.params_to_iolist(:closed, [])
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:190: anonymous fn/3 in :hackney_headers_new.to_iolist/1
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:148: :hackney_headers_new.do_fold/3
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:184: :hackney_headers_new.to_iolist/1
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_request.erl:101: :hackney_request.perform/2
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney.erl:376: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:796: HTTPoison.Base.request/6
```

also happens with :connect_timeout

```
FunctionClauseError) no function clause matching in :hackney_headers_new.params_to_iolist/2 (hackney) 
/home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:201: :hackney_headers_new.params_to_iolist(:connect_timeout, [])
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:190: anonymous fn/3 in :hackney_headers_new.to_iolist/1
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:148: :hackney_headers_new.do_fold/3
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_headers_new.erl:184: :hackney_headers_new.to_iolist/1
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney_request.erl:101: :hackney_request.perform/2
    (hackney) /home/ubuntu/app_build/prod/deps/hackney/src/hackney.erl:376: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:796: HTTPoison.Base.request/6
```
I suspect the connection is closed by the remote, but hackney doesnt know how to handle this?

**Comment by silva96** [comment]
hi @benoitc I see you added this tho a milestone, that means it's a confirmed bug or what?

**Comment by benoitc** [comment]
it means i will ensure to close it this week :) Have been a bit more side tracked than expected but will maintain a release sometimes this week.

**Comment by silva96** [comment]
@benoitc great, take your time. Thanks!

**Comment by achedeuzot** [comment]
For an unknown reason (haven't debugged it in details yet), this crops up with Swoosh when I try to send emails using the  Postmark adapter. Stranger still, this only crashes in production, while it works in development. I'll try to post updates when I find the root cause.
